name: GitHub Archive

on:
  create:
  delete:
  push:
  fork:
  gollum:
  issues:
  issue_comment:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  registry_package:
  release:
  status:
  watch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: 'github-meta'
      - name: Archive event
        uses: githubocto/github-archive-action@v1
