name: GitHub Archive

on:
  issues:
  issue_comment:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  
    
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: 'github-meta'
      - name: Archive event
        uses: githubocto/github-archive-action@main
