name: GitHub Archive

on:
  issues:
  issue_comment:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3
      - name: Archive event
        uses: githubocto/github-archive-action@main
